[package]
name = "melnet2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
concurrent-queue = "1.2.4"
futures-util = "0.3.23"
lz4_flex = "0.9.4"
moka = "0.9.3"
nanorpc = "0.1.1"
pin-project = "1.0.12"
reusable-box-future = "0.2.0"
serde_json = "1.0.83"
smol = "1.2.5"
smol_str = "0.1.23"
smolscale = "0.3.29"
thiserror = "1.0.32"
